//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmniyetPRojesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Icerik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Icerik()
        {
            this.Rapor = new HashSet<Rapor>();
        }
    
        public int IcerikID { get; set; }
        public string Path { get; set; }
        public Nullable<int> BirimID { get; set; }
        public string QR { get; set; }
        public Nullable<int> TurID { get; set; }
        public string URL { get; set; }
        public Nullable<int> YoneticiID { get; set; }
    
        public virtual Birimler Birimler { get; set; }
        public virtual Tur Tur { get; set; }
        public virtual Yonetici Yonetici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rapor> Rapor { get; set; }
    }
}
