//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmniyetPRojesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loglar
    {
        public int LogID { get; set; }
        public string TabloAdi { get; set; }
        public Nullable<System.DateTime> DegisiklikTarihi { get; set; }
        public string DegisiklikYapanKisi { get; set; }
        public string IP { get; set; }
        public string DegisiklikTuru { get; set; }
        public Nullable<int> YoneticiID { get; set; }
    }
}
