//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmniyetPRojesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rapor
    {
        public int RaporID { get; set; }
        public Nullable<int> IcerikID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual Icerik Icerik { get; set; }
    }
}
